---
- name: Create directory for logs
  file:
    path: {{ logs_path }}
    owner: {{ deployment_user }}
    group: docker
    state: directory

- name: Run App
  become: yes
  become_user: {{ deployment_user }}
  docker_container:
    name: {{ app_container_name }}
    image: {{ app_image_url }}
    volumes:
      - {{ logs_path }}:/usr/src/app/logs/
    ports:
      - "3000:3000"
