---
- name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add deployment_user to docker group
  user:
    name: {{ deployment_user }}
    shell: /bin/bash
    group: docker
    append: yes

- name: Run Docker on start
  service:
    name: docker
    state: started
    enabled: yes
